[package]
name = "boringtun"
description = "an implementation of the WireGuardÂ® protocol designed for portability and speed"
version = "0.3.0"
authors = ["Vlad Krasnov <vlad@cloudflare.com>"]
license = "BSD-3-Clause"
repository = "https://github.com/cloudflare/boringtun"
edition = "2018"

[dependencies]
base64 = "0.13"
hex = "0.4"
untrusted = "0.7"
libc = "0.2"
parking_lot = "0.11"
tracing = "0.1.29"
ip_network = "0.3.4"
ip_network_table = "0.1.2"
json = "0.12"

[dependencies.tracing-subscriber]
version = "0.2.25"
optional = true

[dependencies.tracing-appender]
version = "0.1.2"
optional = true

[dev-dependencies]
tracing-subscriber = "0.2.25"

[target.'cfg(not(target_arch="arm"))'.dependencies]
ring = "0.16"

[target.'cfg(not(any(target_os="windows", target_os="ios", target_os="android")))'.dependencies]
clap = { version = "2.33", default-features = false, features = ["suggestions"], optional = true }
daemonize = { version = "0.4.1", optional = true }

[target.'cfg(target_os="android")'.dependencies]
jni = "0.10"

[features]
default = ["build-binary"]
build-binary = ["tracing-subscriber", "tracing-appender", "clap", "daemonize"]

[lib]
crate-type = ["lib", "staticlib", "dylib"]

[[bin]]
name = "boringtun"
path = "src/main.rs"
required-features = ["build-binary"]

[[example]]
name = "benchmarks"
path = "src/benchmarks_example.rs"
