[package]
name = "boringtun"
description = "an implementation of the WireGuardÂ® protocol designed for portability and speed"
version = "0.3.0"
authors = ["Vlad Krasnov <vlad@cloudflare.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/cloudflare/boringtun"
edition = "2018"

[dependencies]
base64 = "0.12"
hex = "0.4"
untrusted = "0.7"
libc = "0.2"
parking_lot = "0.10"
slog = "2.5"
slog-term = "2.5"
ip_network = "0.3.4"
ip_network_table = "0.1.2"

[target.'cfg(not(target_arch="arm"))'.dependencies]
ring = "0.16"

[target.'cfg(not(any(target_os="windows", target_os="ios", target_os="android")))'.dependencies]
chrono = "0.4"
daemonize = "0.4.1"
clap = { version = "2.33", default-features=false, features = ["suggestions"] }

[target.'cfg(target_os="android")'.dependencies]
jni = "0.10"

[lib]
crate-type = ["lib", "staticlib", "dylib"]

[[bin]]
name = "boringtun"
path = "src/main.rs"

[[example]]
name = "benchmarks"
path = "src/benchmarks_example.rs"
