[package]
name = "boringtun"
description = "an implementation of the WireGuardÂ® protocol designed for portability and speed"
version = "0.2.0"
authors = ["Vlad Krasnov <vlad@cloudflare.com>"]
license = "BSD-3-Clause"
readme = "README.md"
repository = "https://github.com/cloudflare/boringtun"
edition = "2018"

[dependencies]
base64 = "0.9.2"
hex = "0.3.2"
untrusted = "0.6.2"
spin = { version = "0.5", default-features=false }
libc = "0.2"

[target.'cfg(not(target_arch="arm"))'.dependencies]
ring = "0.14"

[target.'cfg(not(any(target_os="windows", target_os="ios", target_os="android")))'.dependencies]
chrono = "0.4"
daemonize = "0.4.1"
clap = { version = "2.32.0", default-features=false, features = ["suggestions"] }

[target.'cfg(target_os="android")'.dependencies]
jni = "0.10.2"

[lib]
crate-type = ["lib", "staticlib", "dylib"]

[[bin]]
name = "boringtun"
path = "src/main.rs"

[[example]]
name = "benchmarks"
path = "src/benchmarks_example.rs"
